server:
  port: 15600
spring:
  batch:
    initialize-schema: embedded
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/postgres_real_1?ApplicationName=Prevision-Batch
    username: postgres
    password: 123qwer@
    hikari:
      pool-name: hikari-cp
      maximum-pool-size: 100
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 5000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 10000
        show_sql: false
        use_sql_comments: true
